### ISSUE TITLE
Ipa downlaod?

### ISSUE THREAD

**Issue by memlojr** [anthonya1999/GoodNight#102]
Hey is there an ipa download avalible for GoodNight?

**Comment by salamandercc** [comment]
Hi, Possible to get the IPA for those who do not have a recent mac ?

**Comment by tonytien** [comment]
No. An .ipa would also need to be signed to be run on an unjailbroken device, and that would mean paying $99 for the developer program. You'll have to install the app with Xcode.

**Comment by salamandercc** [comment]
OK thanks.
Another question :
My friend has installed "goodnight" with xcode (on his I6S) but that now lasts 7 days. Is this normal? it was not 90 days? How to do ?

**Comment by tonytien** [comment]
I thought it was also 90 days, I've never encountered that issue. I'm not sure if this is the issue you are experiencing, but I found [this](http://stackoverflow.com/questions/36972118/unable-to-add-apple-id-because-the-10-app-id-limit-in-7-days-has-been-exceed) when I was trying to search for solutions.

**Comment by salamandercc** [comment]
I'm not sure it will solve the problem

Initially Goodnight remained signed the first 90 days. But now the time is 7 days. Not very convenient to reconnect the iDevice every week.

Ideas to keep 90 days after each signature?

**Comment by anthonya1999** [comment]
Hmm, you could try turning off set automatically for your date and time and each day, then keep pushing it back a day. Never tried this, but maybe it's worth a shot?

**Comment by salamandercc** [comment]
No, never tried. But this does not seem very practical. I saw on different forums that Apple now sign for 7 days with free developer accounts. True or false?

**Comment by anthonya1999** [comment]
Well you know what, I wouldn't doubt it. It does make sense. A lot of people are using it for piracy

**Comment by salamandercc** [comment]
Certainly. It was because I had Goodnight. Its remove the yellow tint of my iphone. Now with this restriction that's too bad ... too bad ...

**Comment by anthonya1999** [comment]
Yeah it is, but unfortunately there's nothing I can really do with the project itself to fix the issue, so I'm going to go ahead and close it for now. If I find anything interesting, I'll re-open it and post a comment. Thanks guys!

**Comment by bigmittens** [comment]
@anthonya1999 Would it be possible to push a release every once an a while with an IPA? You can use cydia impactor if you're on a different operating system to sign the IPAs, but I'd rather download from github rather than downloading from somewhere where the IPA may be out of date or maliciously altered.
