### ISSUE TITLE
When you try to enable "Automatic Color Changing", the app just closes. 

### ISSUE THREAD

**Issue by leocrespo** [anthonya1999/GoodNight#39]
Fresh install. ios 9.2. You enable temperature and as soon as you try to enable "Automatic Color Changing" the app just closes (goes back to home).

**Comment by mariokorte** [comment]
Hm. What device are you using? What auto color changing do you select? Location or time? You did use the enabled switch and then enabled one of the auto modes?

Cannot reproduce any of that...

**Comment by mariokorte** [comment]
Also, could you start the App via Xcode, do the aforementioned steps to reproduce the error and then copy the text from the output subview of Xcode (lower right) to here please.

**Comment by iisuuisme** [comment]
Hello! I also have this problem. Mine is an iPhone 4 running iOS 7.1.2 and it crashes after I choose time color changing whether or not the temperature switch is already enabled.

2015-12-15 02:51:51.971 GoodNight[205:60b] -[UIConcreteLocalNotification setAlertTitle:]: unrecognized selector sent to instance 0x15510ba0
2015-12-15 02:51:51.989 GoodNight[205:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIConcreteLocalNotification setAlertTitle:]: unrecognized selector sent to instance 0x15510ba0'
*** First throw call stack:
(0x301e3f83 0x3a994ccf 0x301e7917 0x301e6203 0x30135768 0xb4965 0xa88af 0x32a36037 0x32a35fd7 0x32a35fb1 0x32a21717 0x32c6ceef 0x32c6ca7f 0x32b86fed 0x32a324e3 0x32dd9aed 0x329f9353 0x329f7a9b 0x32a30d49 0x32a3066f 0x32a058cd 0x32a03f77 0x301af20b 0x301ae6db 0x301acecf 0x30117ebf 0x30117ca3 0x3501d663 0x32a6414d 0xb8e0d 0x3aea1ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by iisuuisme** [comment]
Also, on an unrelated issue, my low temperature bedtime mode doesn't seem to work. By that I mean the switch doesn't toggle when I click on it. But I can make a new thread for this problem if that helps!

This app is fantastic btw, thank you so much!!!

**Comment by mariokorte** [comment]
The bedtime mode switch is only enabled (and therefore switchable) when one of the automatic modes is currently active. As you can't seem to get those mode to work atm you cannot see this behavior.

**Comment by mariokorte** [comment]
Should be resolved when pull request #46 is accepted into master.
