### ISSUE TITLE
App Crashing

### ISSUE THREAD

**Issue by scottyd5** [anthonya1999/GoodNight#63]
Just installed the latest build and as always I delete the old version before installing a new one. Followed all the steps since I know this has the new widget so there's extra things to change. Everything installed fine. 

I launch the app and go to enable color changing (location) and the prompt comes up to allow location when using the app, I click allow. The color changing (location) option is still disabled so I try to turn it on again and the app crashes. I try to re-open the app and it crashes on launch. I can't open the app anymore even if I kill it from the task switcher.

Additionally, I tried uninstalling, rebooting and reinstalling GoodNight. Still does the same as I previously said.

Reverted to Dec 20th [build](https://github.com/anthonya1999/GoodNight/tree/f6f3ada1990594042930282a7f8709dba495fffd) before widget and App Groups was added and everything seems fine.

**Comment by pdxvr** [comment]
I had the same experience.  Seems you can change one setting then it crashes, doesn't seem to matter which one you try.

**Comment by milojennings** [comment]
I'm currently experiencing the same issue.

**Comment by mariokorte** [comment]
What iOS version are you using? What devices? Could you run the version from xcode and when it crashes give me the output from the sub-window in the lower right corner?

**Comment by mariokorte** [comment]
Did you check you edited all IDs mentioned in https://github.com/anthonya1999/GoodNight/blob/master/Help/README.md? This is crucial.

**Comment by schnizki** [comment]
Had the exact Same issus, just forgot to edit the prefixheaders.pch. Now its Working Fine ;)

**Comment by anthonya1999** [comment]
@schnizki Awesome to hear!

**Comment by pdxvr** [comment]
iPhone 6S, iOS 9.2, 

2015-12-24 11:17:28.386 GoodNight[331:17326] *** Assertion failure in +[GammaController setGammaWithTableAndRed:green:blue:], /Users/mmm/Documents/GoodNight/GoodNight/GammaController.m:124
2015-12-24 11:17:28.388 GoodNight[331:17326] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: file != NULL'
*** First throw call stack:
(0x1817d5900 0x180e43f80 0x1817d57d0 0x18214899c 0x100053d44 0x100053554 0x100054238 0x100055358 0x100040110 0x1864ffe50 0x1864ffdcc 0x1864e7a88 0x1868b27d0 0x186508544 0x1864b8294 0x1864f8820 0x1864f7e1c 0x1864c84cc 0x1864c6794 0x18178cefc 0x18178c990 0x18178a690 0x1816b9680 0x182bc8088 0x186530d90 0x1000516d8 0x18125a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by mariokorte** [comment]
@pdxvr this smells very very much like wrong group id in prefixheaders, just like @schnizki.

If that is not the case then my next guess would be malconfigured app groups. Did you check that under capabilities xcode doesn't complain anything about the app groups? And that for both: widget and app!

Please check!

**Comment by pdxvr** [comment]
I've now triple checked it. Prefix headers, app groups, team, both app and widget, no warnings in xcode, same error.  Restarted xcode, rebooted phone too.

**Comment by mariokorte** [comment]
This is definitely a configuration error. The file is null because you are trying to access a space for the group on the file system via containerURLForSecurityApplicationGroupIdentifier which the system does not allow you to access (because of a configuration error).
Can you zip and upload your project somewhere that I can take a closer look?

**Comment by pdxvr** [comment]
Is there any sensitive info in there?

**Comment by mariokorte** [comment]
No, not really.

**Comment by pdxvr** [comment]
http://kunamakst.com/other/GoodNight.zip

**Comment by mariokorte** [comment]
Didn't check so thoroughly the last three times, did ya? ;)

Two errors:
- PrefixHeader.pch still contains '#define appGroupID @"group.com.adatech.goodnight"'
 change this to the group name you selected in "Capabilities -> App Groups"

- Also: your app id prefix is "com.pdxvr.goodnight", but you group name under "Capabilities -> App Groups" is "group.com.pdxvr.goognight"

Notice the gooGnight (!!) in your group name?

Change all these and it should run. Please delete app completely from phone and reinstall after changes are made.

**Comment by pdxvr** [comment]
I'd pulled the files a few times so the pch file was new this time

**Comment by mariokorte** [comment]
OK, let me know if everything works out fine for you.

**Comment by scottyd5** [comment]
prefixheaders.pch editing is what I missed also. Sorry about that. User error. It's a little more buried in there than the other things that need to be changed. 

Might be helpful to other newbies if you include a screenshot in the Readme where to find the prefixheaders.pch and what to edit.

**Comment by pdxvr** [comment]
works fine, thanks!

**Comment by mariokorte** [comment]
Yes, already working on that. But the textual description is already there. ;)

**Comment by mariokorte** [comment]
\o/

**Comment by milojennings** [comment]
Even though I quadruple checked, the issue ended up being the group name. 
I was missing `.com`. It should be `group.com.<something>.goodnight` instead of `group.<identifier>.goodnight`. My bad.

Now it's working perfectly, and I couldn't be more excited to finally have a night friendly iPhone screen.
