### ISSUE TITLE
Temperature setting switches to default randomly

### ISSUE THREAD

**Issue by insmac** [anthonya1999/GoodNight#8]
iOS 9.1, iPhone 6s. Compiled with Xcode 7.1

iOS reverts back to a default temperature in a random manner (i.e. browsing AppStore, loading Facebook or any other third-party apps). Going back to GoodNight app fixes it for another few hours. 

Happens both in manual and automatic mode.

**Comment by anthonya1999** [comment]
Huh, that is quite strange. I did not have this issue on iOS 9.1 or 9.2 beta (which I am currently running). I will check over the code to make sure there isn't an error anywhere. Thanks for pointing this out!

**Comment by insmac** [comment]
I'll create a screencast today if that helps.

**Comment by designeq** [comment]
IOS 9.1, iPad Air 2
I can confirm Inseam's report of "random" reverting to default temperatures. When staying within one app (iBooks) I noticed that this happened every 30 minutes, almost to the minute. Other times I noticed this switch seemed to be when switching to a different application.

**Comment by anthonya1999** [comment]
Hmm, interesting...my guess would be it would have to do with the automatic color changing mode, or the "waking up screen if needed" function.

**Comment by designeq** [comment]
On continuing to use the app, these observations continue to hold—turning off at exactly 30 minutes (although occasionally it happens at a different time frame) and turning off upon switching apps. BTW, I know you've said that automatic mode isn't precise, but I've never seen it work, ever. It never turns on the  temperature setting change and it never turns it off. I've left it at the default settings of 7pm/7am though, so I haven't tested it much.

One other observation: when I switch to your app (in order to bring back the temperature color after it switches off by itself—just switching to your app turns it back on—I've been noticing a temperature "fluctuation" on the screen when entering your app. It's as though it is cycling the temperature setting on and off 5 or 6 times in rapid succession, causing a color fluttering to occur. Strange!

I *love* this app and really hope you continue to work on it. I will be happy to provide future feedback as I observe things.

**Comment by helloHK** [comment]
My observation with the use of this app, with automatic mode on, it never seems to work at all. Background app refresh for the app is confirmed to be turn on. Waiting for almost 30min and it doesn't switch on automatically.

**Comment by anthonya1999** [comment]
This should be fixed with the latest pull request.
